### ISSUE TITLE
The terminal YouTube player seems unable to play videos

### ISSUE THREAD

**Issue by sudo-daemon** [sayan01/scripts#1]
![yt-player-errors](https://user-images.githubusercontent.com/76221621/103194979-33da9c00-48d9-11eb-8b1d-26edac71056c.png)
This occurs whenever I select a video to play.

**Comment by sujanchegu** [comment]
+1 for me

**Comment by sayan01** [comment]
unable to replicate.
 do you have `mpv` and `youtube-dl` installed? maybe try running a normal youtube link (in the format `mpv https://youtu.be/videoid`) through mpv and see if its a problem with your youtube-dl or not.

**Comment by sujanchegu** [comment]
I actually don't have that installed at all. I'll check how to download
that first. Thanks.
